name: report-cards
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Criticisms
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141215'
    - '#eaf0f0'
    - '#c59d60'
    - '#3c3b40'
    - '#c15166'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
