name: report-cards
favicon: null
layout_spectrum: 0.24271
typography_spectrum: 0.9040183681063354
title: Criticisms
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.39597522048279643
  lightness: 0.5080514834262431
  saturation: 0.09505452588200569
  rhythmicContrast: 0.8371304520405829
purpose: []
